### ISSUE TITLE
New User-Register and create a user account-Gaining access to the platform

### ISSUE THREAD

**Issue by luliuzh** [sopra-fs24-group-18/sopra-fs24-group-18-client#1]
**Acceptance Criteria:**
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#2
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#3
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#4
- [x] sopra-fs24-group-18/sopra-fs24-group-18-server#5
- [ ] sopra-fs24-group-18/sopra-fs24-group-18-server#6
