### ISSUE TITLE
4.2 Implement Route Protector for Smoother Gaming Experience

### ISSUE THREAD

**Issue by luliuzh** [sopra-fs24-group-18/sopra-fs24-group-18-client#74]
#### Tasks
- [ ] 4.2.1 Implement route protector to restrict unauthorized access to each page.
- [ ] 4.2.2 Handle Browser Back and Refresh Events for User Navigation
- [ ] 4.2.3 Clear local storage upon window/tab closure to prevent data leakage and maintain security.
